name: Build and push to AWS

on:
  push:
    branches:
     - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v3

      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with: 
       dotnet-version: '8.0'

      
    - name: Build project
      working-directory: MyencryptAPI  
      run: |
        dotnet restore
        dotnet build --configuration Release

     
      
    - name: Build and publish
      working-directory: MyencryptAPI  
      run: dotnet publish MyencryptAPI.csproj --configuration Release --output site

    
      
    - name: Create zip package
      working-directory: MyencryptAPI/site
      run: zip -r ../../site.zip *

      
    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: CICDAPI
        environment_name: CICDAPI-env
        version_label: ${{ github.run_id }}
        region: eu-north-1
        deployment_package: site.zip