name: Build and push to aws

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '9.0'

      - name: Build project  
        run: dotnet restore; dotnet publish -o site;